version: "1"

services:
  - type: web
    name: video-platform-signaling
    runtime: docker
    repo: https://github.com/jorishi9617/signaling-service
    branch: master
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: checksPass
    healthCheckPath: /actuator/health
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_ORIGINS
        sync: false
